[repo]
kind = "std-recipe"

[[repo-ref]]
dir = "app/code.ap.toml"

[[repo-ref]]
dir = "app/ptyxis.ap.toml"

[[repo-ref]]
dir = "app/dolphin.ap.toml"

[[repo-ref]]
dir = "app/chrome.ap.toml"

[[repo-ref]]
dir = "game/oni.ap.toml"