[[match]]
class = "code"

[default]
background = "Lime"
size = 0.75

[[button]]
icon = "fullscreen"
bottom = "Fullscreen"
actions = [ { type = "+F11" } ]
background = "blue"

[[button]]
icon = "content_copy"
bottom = "Copy"
actions = [ { type = "+Copy" } ]
background = "blue"

[[button]]
icon = "content_cut"
bottom = "Cut"
actions = [ { type = "+Cut" } ]
background = "blue"

[[button]]
icon = "content_paste"
bottom = "Paste"
actions = [ { type = "+Paste" } ]
background = "blue"

[[button]]
icon = "code"
bottom = "Cmd"
actions = [ { type = "Ctrl+Shift+P" } ]

[[button]]
icon = "terminal"
bottom = "Terminal"
actions = [ { type = "Ctrl+Shift+`" } ]

[[button]]
icon = "start"
bottom = "Run"
actions = [ { type = "+F5" } ]

[[button]]
icon = "pause"
bottom = "Pause"
actions = [ { type = "+F4" } ]

[[button]]
icon = "arrow_forward"
bottom = "Step"
actions = [ { type = "+F8" } ]

[[button]]
icon = "arrow_downward"
bottom = "Step in"
actions = [ { type = "+F11" } ]

[[button]]
icon = "arrow_upward"
bottom = "Step out"
actions = [ { type = "Shift+F8" } ]

[[button]]
icon = "replay"
bottom = "Restart"
actions = [ { type = "Ctrl+Shift+F5" } ]

[[button]]
icon = "stop"
bottom = "Stop"
actions = [ { type = "Shift+F5" } ]
background = "red"


