[[match]]
class = "code"

[default]
# Defaults values for buttons that don't specify them explicitly
background = "0x00ff0080" # Greenish

[[button]]
icon = "code"
bottom = "Cmd"
actions = [ { type = "Ctrl+Shift+P" } ]

[[button]]
icon = "terminal"
bottom = "Terminal"
actions = [ { type = "Ctrl+Shift+`" } ]

[[button]]
icon = "start"
bottom = "Run"
actions = [ { type = "F5" } ]

[[button]]
icon = "pause"
bottom = "Pause"
actions = [ { type = "F4" } ]

[[button]]
icon = "step_over"
bottom = "Step"
actions = [ { type = "F8" } ]

[[button]]
icon = "step_into"
bottom = "Step in"
actions = [ { type = "F11" } ]

[[button]]
icon = "step_out"
bottom = "Step out"
actions = [ { type = "Shift+F8" } ]

[[button]]
icon = "replay"
bottom = "Restart"
actions = [ { type = "Ctrl+Shift+F5" } ]

[[button]]
icon = "stop"
bottom = "Stop"
actions = [ { type = "Shift+F5" } ]
background = "0xff000080" # Reddish


