[[match]]
class = "org.gnome.Ptyxis"

[default]
background = "Cyan" 
size = 0.75

[[button]]
icon = "fullscreen"
bottom = "Fullscreen"
actions = [ { type = "+F11" } ]
background = "blue"

[[button]]
icon = "content_copy"
bottom = "Copy"
actions = [ { type = "Shift+Ctrl+C" } ]
background = "blue"

[[button]]
icon = "content_paste"
bottom = "Paste"
actions = [ { type = "Shift+Ctrl+V" } ]
background = "blue"

[[button]]
icon = "add_to_photos"
bottom = "New Tab"
actions = [ { type = "Ctrl+Shift+T" } ]

[[button]]
icon = "arrow_back"
top = "Previous"
bottom = "Tab"
actions = [ { type = "Ctrl+PageUp" } ]

[[button]]
icon = "arrow_forward"
top = "Next"
bottom = "Tab"
actions = [ { type = "Ctrl+PageDown" } ]

[[button]]
icon = "stop"
bottom = "Break"
actions = [ { type = "Ctrl+C" } ]
background = "red"


