[[match]]
class = "org.gnome.Ptyxis"

[default]
background = "Cyan" 
size = 0.75

[[button]]
icon = "fullscreen"
bottom = "Fullscreen"
actions = [ { type = "+F11" } ]
background = "blue"

[[button]]
icon = "content_copy"
bottom = "Copy"
actions = [ { type = "+Copy" } ]
background = "blue"

[[button]]
icon = "content_cut"
bottom = "Cut"
actions = [ { type = "+Cut" } ]
background = "blue"

[[button]]
icon = "content_paste"
bottom = "Paste"
actions = [ { type = "+Paste" } ]
background = "blue"

[[button]]
icon = "add_to_photos"
bottom = "New Tab"
actions = [ { type = "Ctrl+Shift+T" } ]

[[button]]
icon = "arrow_back"
bottom = "Previous Tab"
actions = [ { type = "Ctrl+PageUp" } ]

[[button]]
icon = "arrow_forward"
bottom = "Next Tab"
actions = [ { type = "Ctrl+PageDown" } ]

[[button]]
icon = "stop"
bottom = "Break"
actions = [ { type = "Ctrl+C" } ]
background = "red"


